apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort   # external access ke liye
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # service port
      targetPort: 80  # container port
      nodePort: 30007 # fixed port (easy for demo)